### ISSUE TITLE
Can runtime.LockOSThread exit a thread?

### ISSUE THREAD

**Issue by geekrichie** [golang-design/mkill#3]
your code exit a thread look like this 
```
go func() {     
	runtime.LockOSThread()  
	wg.Done()  
}()  
```
I think you should add a line of code to exit the thread
```
go func() {     
	runtime.LockOSThread()  
        syscall.Syscall(syscall.SYS_EXIT, 0, 0, 0)
	wg.Done()  
}()  
```

**Comment by changkun** [comment]
```
go func() {     
	runtime.LockOSThread()  
	wg.Done()  
}()
```

This pattern is runtime implementation-specific. See: https://github.com/golang/go/blob/4847c47cb8a93b56e1df8c249700e25f527d4ba3/src/runtime/proc.go#L3669-L3683

**Comment by changkun** [comment]
syscall.SYS_EXIT is nice but does not exist on Windows.

**Comment by changkun** [comment]
Due to the comments above, there is nothing to fix. Close

**Comment by geekrichie** [comment]
thanks for you help, I saw the comments.
